version: '2.1'

services:
  my-tpm-consumption:
    image: my-tpm-consumption
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js